sudo: false

services:
  - docker

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack: bsf-bots:RDGCoMDDxnlCvnUfvhq8pQ36

cache:
  - $HOME/.composer/cache

jobs:
  fast_finish: true
  allow_failures:
    - env: ALLOW_FAILURES=1
  include:

    - name: Lint
      name: Lint (PHP, JavaScript, and configuration files)
      php: "7.3"
      env: WP_VERSION=latest
      before_script:
        - |
         if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
            composer install
         fi
      script:
        - |
          if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
            vendor/bin/phpcs
          fi
        - if find . -name "*.php" ! -path "./vendor/*" ! -path "./admin/bsf-core/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi

    - name: E2E tests
      php: "7.3"
      env: WP_VERSION=latest PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=
      install:
        - nvm install
      script:
        - npm run env:start
        # - npm run env:reset-site
        - npm run test:e2e:ci
        - npm run env:stop
