name: CI And Audits

# Run the deployment only when code is committed to the branch.
on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.pull_request.head.sha }}

    - name: Get npm cache directory
      id: npm-cache
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Configure npm cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: npm install, build
      run: |
        npm install

    - name: Start Docker environment
      run: npm run env:start
      env:
        COMPOSE_INTERACTIVE_NO_CLI: true

    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        # Any JS files anywhere within a dist directory:
        pattern: "{assets/**/**/*.js,assets/**/**/*.css}"

        # Always ignore SourceMaps and node_modules:
        exclude: "{**/*.map,**/node_modules/**}"
        build-script: "dynamic-css"

    # compressed-size-action checks out to base branch but does not revert back to current branch.
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.7.x
        lhci autorun --collect.settings.chromeFlags='--no-sandbox'
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

    - name: Stop Docker environment
      run: npm run env:stop
      if: always()
      env:
        COMPOSE_INTERACTIVE_NO_CLI: true
