name: Theme Check

on:
    push:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        name: Theme Check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Use desired version of NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15

            - name: Cache NPM packages
              uses: actions/cache@v2
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ matrix.node }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

            - name: Find MD5 of wp-env
              run: echo "CONFIG_MD5=$(echo -n echo $PWD/.wp-env.json | md5sum)" >> $GITHUB_ENV

            - name: Check Var
              run: echo $env.CONFIG_MD5 && echo $CONFIG_MD5

            - name: Start Docker Environment
              run: npm run env:start

            - name: Install Theme Check package
              run: docker-compose -f $HOME/$CONFIG_MD5/docker-compose.yml run -e WP_CLI_PACKAGES_DIR=.wp-cli --rm cli wp package install anhskohbo/wp-cli-themecheck && npm run wp-env run cli wp plugin install theme-check --version=20200922.1 --activate

            - name: Theme Check
              run: npm run wp-env run cli wp themecheck

