name: Theme Check

on:
   pull_request:
       branches:
       - next-release
       - release-candidate
       - master

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        name: Theme Check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Cache NPM packages
              uses: actions/cache@v2
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ matrix.node }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              run: npm install

            - name: Start Local Environment
              run: npm run env:start
              env:
                COMPOSE_INTERACTIVE_NO_CLI: true

            - name: Find MD5 of wp-env
              run: echo "CONFIG_MD5=$(echo $(echo -n "$PWD/.wp-env.json" | md5sum) | sed -e "s/ -//")" >> $GITHUB_ENV

            - name: Install Theme Check package
              run: docker-compose -f $HOME/wp-env/$CONFIG_MD5/docker-compose.yml run -e WP_CLI_PACKAGES_DIR=.wp-cli --rm cli wp package install anhskohbo/wp-cli-themecheck

            - name: Install Theme Check Plugin
              run: docker-compose -f $HOME/wp-env/$CONFIG_MD5/docker-compose.yml run -e WP_CLI_PACKAGES_DIR=.wp-cli --rm cli wp plugin install theme-check --version=20200922.1 --activate

            - name: Theme Check
              run: docker-compose -f $HOME/wp-env/$CONFIG_MD5/docker-compose.yml run -e WP_CLI_PACKAGES_DIR=.wp-cli --rm cli wp themecheck --theme=astra --no-interactive

            - name: Stop Docker environment
              run: npm run env:stop
              if: always()
              env:
                COMPOSE_INTERACTIVE_NO_CLI: true
