name: Check MD5

on:
    pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        name: Check
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['12']
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Find MD5
              run: echo -n Welcome | md5sum
