name: Theme Check

on:
    push:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        name: Theme Check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Use desired version of NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15

            - name: Cache NPM packages
              uses: actions/cache@v2
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ matrix.node }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

            # - name: Install Dependencies
            #   run: npm install

            - name: Add temp files
              run: echo $(md5sum <<<"$PWD/.wp-env.json")

            # - name: Start Local Environment
            #   run: npm run env:start
            #   env:
            #     COMPOSE_INTERACTIVE_NO_CLI: true

            # - name: path of wp-env config
            #   run: ls -lsha && echo $PWD/.wp-env.json && cat $PWD/.wp-env.json

            # - name: Find MD5 of wp-env
            #   run: echo "CONFIG_MD5=$(echo $(echo $PWD/.wp-env.json | md5sum) | sed -e "s/ -//")" >> $GITHUB_ENV

            # - name: Docker Path
            #   run: ls -lsha $HOME/ && ls -lsha $HOME/wp-env/ && ls -lsha $HOME/wp-env/$CONFIG_MD5/

            - name: Stop Docker environment
              run: npm run env:stop
              if: always()
              env:
                COMPOSE_INTERACTIVE_NO_CLI: true
