name: Update pull request

# Run the deployment only when code is committed to the branch.
on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - edited
      - opened

jobs:
  update-branch:
    runs-on: ubuntu-latest
    name: Updating Branch
    if: ${{ github.event.label.name == 'update-branch' }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update the branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git pull origin development
          git push origin HEAD:${GITHUB_REF}
